name: Build/Deploy Dependencies
on:
  push:
    branches: [ main ]
    paths:
      - '**/PrejittedLambda.Dependencies/*'
  workflow_dispatch:
  
jobs:
  pipeline:
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install tools
        run: |
          npm install -g aws-cli   
          dotnet tool install -g Amazon.Lambda.Tools                
      - name: Deploy Lambda Layer
        run: |
          cd PrejittedLambda.Dependencies
          dotnet lambda publish-layer PrejittedLambdaDependencies --layer-type runtime-package-store --s3-bucket prejittedlambdadependencies290387498273498 --framework netcoreapp3.1
