name: Build/Deploy
on:
  push:
    branches: [ build ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v2
      - name: Setup .NET 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test
      - name: Install cdk
        run: |
          npm install -g aws-cdk
      - name: Deploy
        run: cdk deploy "*" --require-approval never